"""added status column to task table

Revision ID: 4c3b5ac1d580
Revises: f06ff27358ed
Create Date: 2025-05-22 13:22:55.814644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3b5ac1d580'
down_revision: Union[str, None] = 'f06ff27358ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = sa.Enum('pending', 'in_progress', 'completed', name='status_enum')
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='status_enum'), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    op.execute("DROP TYPE IF EXISTS status_enum")
    # ### end Alembic commands ###
