"""add created by id to tasks table

Revision ID: f06ff27358ed
Revises: 96bba07fc6dc
Create Date: 2025-05-21 13:58:35.538890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06ff27358ed'
down_revision: Union[str, None] = '96bba07fc6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    op.create_foreign_key("fx_tasks_created_by_id", 'tasks', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fx_tasks_created_by_id', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    op.drop_column('tasks', 'created_by_id')
    # ### end Alembic commands ###
